sudo: required

services:
  - docker

before_install:
  - docker pull jimexist/docker-hive:v2.1.1
  - docker build -t jimexist/simple-hive-presto .
  - docker run -d --hostname hive --name hive jimexist/docker-hive:v2.1.1
  - docker run -d --hostname presto --link hive --name presto -p 127.0.0.1:8080:8080 jimexist/simple-hive-presto

script:
  - docker logs hive
  - docker logs presto
